events:
  driverClass: com.mysql.jdbc.Driver
  user: example
  password: example
  url: jdbc:mysql://events-db:3306/events?useSSL=false
  validationQueryTimeout: 10s

snapshots:
  driverClass: com.mysql.jdbc.Driver
  user: example
  password: example
  url: jdbc:mysql://snapshots-db:3306/snapshots?useSSL=false
  validationQueryTimeout: 10s
